services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./set_game_project:/app/set_game_project
      - static_volume:/app/set_game_project/staticfiles
    expose:
      - 8000
    depends_on:
      - redis
    networks:
      - board_game_site_app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/set_game_project/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - board_game_site_app-network

  redis:
    image: redis:latest
    sysctls:
      - vm.overcommit_memory=1
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - board_game_site_app-network

volumes:
  static_volume:


networks:
  board_game_site_app-network:
    driver: bridge
