# Generated by Django 5.0.6 on 2024-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='state',
            field=models.JSONField(default=dict),
        ),
    ]
