# Generated by Django 5.0.6 on 2025-02-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_game', '0003_lobby_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='lobby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='set_game.lobby'),
        ),
    ]
